Version bump
leaningtech/labs pull request #162
Opened 2024-11-04 08:50 UTC by AtibQur

2024-11-04 09:12 UTC, alexp-sssup commented
Please rework this to have a single variable controlling the version everywhere

2024-11-07 09:31 UTC, alexp-sssup requested changes
Current solution does not work. Try to get a better understanding about how the ``` actually works. We want to get the same rendering style using HTML directly.

2024-11-07 09:31 UTC, alexp-sssup commented on sites/cheerpx/src/content/docs/10-getting-started/index.mdx
> +	import * as CheerpX from "https://cxrtnc.leaningtech.com/{VERSION_NUMBER}/cx.esm.js";
This does not work, as expected
![image](https://github.com/user-attachments/assets/5d87d68b-f498-4026-bdc1-8f24b5380e52)

Please use a local build, it does not make sense for me to review a not yet working solution

2024-11-11 11:48 UTC, closed without merging

2024-11-11 11:48 UTC, AtibQur commented
I think I've fixed the problem. I'm closing this PR/branch and will make a new PR with another branch