updated native methods guide
leaningtech/labs pull request #167
Opened 2024-11-11 10:13 UTC by theodoravraimakis

2024-11-11 14:37 UTC, epanholz commented on sites/cheerpj/src/content/docs/11-guides/implementing-native-methods.md
> +
We could already add the steps that we will explain here, something like "Adding natives to CheerpJ only requires a few steps: 1. Define a native function in Java 2. Implement it in Java Script 3. Pass it to CheerpJ". You could also a bit of context why natives would be useful.

2024-11-11 14:37 UTC, epanholz commented on sites/cheerpj/src/content/docs/11-guides/implementing-native-methods.md
> +
We should add a part here that already shows how to add the native function in Java, maybe a header before the `Implementing Native Methods in JavaScript` and call it something like `How do add a native function to Java` and just show the same example class.

The old docs also had a part about the naming that was very clear, please add this:
`Java_<fully-qualified-class-name>_<method-name>` - For instance, if com.foo.Bar has a native method called `baz`, its object key is `Java_com_foo_Bar_baz`.

2024-11-11 14:38 UTC, epanholz commented on sites/cheerpj/src/content/docs/11-guides/implementing-native-methods.md
> +
We should add the full HTML code here to make it clear where the function is defined.

2024-11-11 14:43 UTC, epanholz commented on sites/cheerpj/src/content/docs/11-guides/implementing-native-methods.md
> +2. Implement the native method by creating an `async` function in JavaScript that follows the naming convention `Java_<ClassName>_<MethodName>`.
You should use `Java_<fully-qualified-class-name>_<method-name>` instead of `Java_<ClassName>_<MethodName>` to make it more clear.

2024-11-18 11:31 UTC, epanholz approved these changes
This one looks good to me know. For the future please `--amend` to the first commit if I request some changes, to avoid unnecessary commits. Keeps the history clean.

2024-11-19 14:31 UTC, GabrielaReyna requested changes
Thanks for the PR and great work. I have suggested a couple ofchanges regarding formatting. 

I'd like to ask about the difference between this guide and "Implementing native methods and libraries". We will probably need to rename these guides to make it less confusing for the user since them two have very similar titles.

2024-11-19 14:31 UTC, GabrielaReyna commented on sites/cheerpj/src/content/docs/11-guides/implementing-native-methods.md
> +CheerpJ allows you to implement Java native methods (typically written in C/C++ or another AOT-compiled language) directly in JavaScript, similar to the Java Native Interface (JNI) in standard Java.
```suggestion
CheerpJ allows one to implement Java native methods (typically written in C/C++ or another AOT-compiled language) directly in JavaScript, similar to the Java Native Interface (JNI) in standard Java.
```

2024-11-19 14:31 UTC, GabrielaReyna commented on sites/cheerpj/src/content/docs/11-guides/implementing-native-methods.md
> +To implement a native method in JavaScript, create an `async` function that follows the naming convention `Java_<fully-qualified-class-name>_<method-name>`. For instance, if com.foo.Bar has a native
```suggestion
To implement a native method in JavaScript, create an `async` function that follows the naming convention `Java_<fully-qualified-class-name>_<method-name>`. For instance, if `com.foo.Bar` has a native method called `baz`, its object key is `Java_com_foo_Bar_baz`. The function takes:
```

2024-11-19 14:31 UTC, GabrielaReyna commented on sites/cheerpj/src/content/docs/11-guides/implementing-native-methods.md
> +[`conversion rules`]: /docs/reference/CJ3Library#conversion-rules
```suggestion
[`conversion rules`]: /docs/reference/CJ3Library#conversion-rules
[`cheerpjInit`]: /docs/reference/cheerpjInit
```

2024-11-19 14:31 UTC, GabrielaReyna commented on sites/cheerpj/src/content/docs/11-guides/implementing-native-methods.md
> +To use the native method in CheerpJ, pass the function to the `cheerpjInit` function as a property of the [`natives`] option. You can pass:
```suggestion
To use the native method in CheerpJ, pass the function to the [`cheerpjInit`] function as a property of the [`natives`] option. You can pass:
```

2024-11-19 14:31 UTC, GabrielaReyna commented on sites/cheerpj/src/content/docs/11-guides/implementing-native-methods.md
> +3. Initialize CheerpJ with the `natives` option and pass the native method implementation to `cheerpjInit`:
```suggestion
3. Initialize CheerpJ with the `natives` option and pass the native method implementation to [`cheerpjInit`]:
```

2024-11-19 14:31 UTC, GabrielaReyna commented on sites/cheerpj/src/content/docs/11-guides/implementing-native-methods.md
> +In this setup, `cheerpjInit` loads `Java_Example_alert` as the native method implementation. When `Example.alert` is called in Java, it triggers the JavaScript `Java_Example_alert` function, displayi
```suggestion
In this setup, [`cheerpjInit`] loads `Java_Example_alert` as the native method implementation. When `Example.alert` is called in Java, it triggers the JavaScript `Java_Example_alert` function, displaying an alert dialog with the message.
```

2024-11-19 14:37 UTC, epanholz commented
We decided to split the "Implementing native methods and libraries" guide into two separate ones, we heard from some customer that it is a bit difficult to understand so we also revamped them a bit. There is another PR with the standalone libraries guide.

2024-11-25 13:59 UTC, GabrielaReyna approved these changes

2024-11-25 14:01 UTC, merged