Added processCreated section
leaningtech/labs pull request #195
Opened 2024-12-07 07:03 UTC by AtibQur

2024-12-09 07:53 UTC, alexp-sssup requested changes

2024-12-09 07:53 UTC, alexp-sssup commented on sites/cheerpx/src/content/docs/12-reference/20-CheerpX-linux-callbacks.md
> +	if (processCallback) processCallback(processCount);
Calling another callback is redundant here, this is already a callback and the user can run arbitrary logic here

2024-12-09 10:17 UTC, alexp-sssup approved these changes

2024-12-09 17:40 UTC, GabrielaReyna requested changes
Thanks for adding this information. A couple of things:
- I am finding this page hard to navigate. There may be a better way to organise subtitles in order to show the subsections on the table of contents. For example, making the parameters and returns nested subtitles. 
- I  understand the info here is dense and required it's own page. Please link this page reachable from ´/CheerpX-Linux-create#returns´. I'm also thinking if part of this should go under CheerpX-Linux-create + a guide. Let's discuss this with Alessandro.

2024-12-10 15:25 UTC, GabrielaReyna approved these changes

2024-12-10 15:27 UTC, merged