Added edit /etc/subgid section
leaningtech/labs pull request #199
Opened 2024-12-14 14:45 UTC by AtibQur

2024-12-16 07:47 UTC, alexp-sssup requested changes

2024-12-16 07:47 UTC, alexp-sssup commented on sites/cheerpx/src/content/docs/11-guides/custom-images.mdx
> +nobody:100000:65536
Wait, I am not sure about this. I have a vague recollection that the user that needs to be changed is the _current_ user, the id inside the container is irrelevant here. Can you validate?

2024-12-16 07:47 UTC, alexp-sssup commented on sites/cheerpx/src/content/docs/11-guides/custom-images.mdx
> +sudo systemctl restart podman
Is this actually required?

2024-12-16 11:04 UTC, alexp-sssup commented
@AtibQur Can you confirm this has been validated as working?

2024-12-17 13:05 UTC, AtibQur commented
@alexp-sssup for some reason I keep getting Error: cannot setup namespace using newuidmap: exit status 1. 

This happens when I'm using: podman run --rm -it --userns=keep-id alpine to start a podman container with user namespace even though uidmap is already installed on my system.
Do you have any idea/experience how to deal with this or how to test it in another way?

2024-12-17 13:31 UTC, alexp-sssup commented
I have never seen this error and I think `--userns=keep-id` is not correct, I certainly did never use it

2024-12-19 14:19 UTC, AtibQur commented
@alexp-sssup I've been testing changes to /etc/subgid while running podman containers to see how group IDs are mapped. The changes are working as expected for /etc/subgid.
I was wondering if I need to also write about changing /etc/subuid to ensure proper mapping for both UIDs and GIDs

2025-01-07 09:14 UTC, alexp-sssup approved these changes

2025-01-07 17:04 UTC, GabrielaReyna requested changes

2025-01-07 17:04 UTC, GabrielaReyna commented on sites/cheerpx/src/content/docs/11-guides/custom-images.mdx
> +## Edit `/etc/subgid` (for the host user)
I noticed this guide has a step 1,2,3 format: 

- Is this section a step within the 1,2,3 etc? If so, please add the number. If is not a mandatory step but an optional action, please specify so within the text in the first paragraph of this section. 
- Please also specify at the end of the "Last step" that until that point things should work or that the setup is complete and what the user can expect at the end of the guide.

2025-01-08 17:30 UTC, GabrielaReyna approved these changes

2025-01-08 17:31 UTC, merged