First GPOs guide draft
leaningtech/labs pull request #81
Opened 2024-05-07 17:23 UTC by GabrielaReyna

2024-05-08 02:08 UTC, bates64 commented
Tests are failing because of https://github.com/leaningtech/labs.leaningtech.com/issues/80

2024-05-13 21:51 UTC, bates64 requested changes

2024-05-13 21:51 UTC, bates64 commented on src/content/docs/cheerpj-jnlp-runner/04-guides/private-hosting-chrome.mdx
> +You will need to download and install the Google administrative templates. You can do this by downloading the templates file and following the steps as stated in this [guide by google](https://suppor
This should be a button

2024-05-13 21:51 UTC, bates64 commented on src/content/docs/cheerpj-jnlp-runner/04-guides/private-hosting-chrome.mdx
> +For more information about extension settings visit [The Chrome Documentation](https://support.google.com/chrome/a/answer/9867568?hl=en)
Also button

2024-05-13 21:51 UTC, bates64 commented on src/content/docs/cheerpj-jnlp-runner/04-guides/private-hosting-chrome.mdx
> +## The CRX File and Download URL
Given it's called `DownloadURL` in Google's API, I'd start calling it DownloadURL instead of "the Download URL"

2024-05-13 21:51 UTC, bates64 commented on src/content/docs/cheerpj-jnlp-runner/04-guides/private-hosting-chrome.mdx
> +> [!info] About the Download URL
```suggestion
> [!info] About `DownloadURL`
```
(This markdown might not get formatted, in which case I need to raise an issue in another project / go fix it but we can merge anyway)

2024-05-13 21:51 UTC, bates64 commented on src/content/docs/cheerpj-jnlp-runner/04-guides/private-hosting-chrome.mdx
> +You will need to host the extension CRX file in the appropriate location of your IT infrastructure and create a download URL to access it. You will need this URL later in the tutorial.
Embolden this
```suggestion
**Host the extension CRX file in an appropriate location in your IT infrastructure and create a download URL to access it.** You will need this URL later in the tutorial.
```

2024-05-13 21:51 UTC, bates64 commented on src/content/docs/cheerpj-jnlp-runner/04-guides/private-hosting-chrome.mdx
> +They Key **(_\*_)** will apply the settings to all extensions or apps under this policy.
Typo
```suggestion
The Key **(_\*_)** will apply the settings to all extensions or apps under this policy.
```

2024-05-20 15:34 UTC, GabrielaReyna commented
I'm getting broken link errors, it is trying to map to the older cheerpj-jnlprunner url. Any ideas on how to fix this?

2024-05-22 11:22 UTC, bates64 commented
Commit https://github.com/leaningtech/labs/pull/81/commits/94d45ec816d32b0d449ea190a21f935a251f22e9 could have "fix #80" in the commit message so GitHub knows to close the issue when it is merged. See https://docs.github.com/en/issues/tracking-your-work-with-issues/closing-an-issue. I'll edit the PR description instead in this instance

2024-05-22 11:24 UTC, bates64 commented
Do we prefer that Stefano reviews this? If my changes were resolved I'm happy

2024-05-22 13:09 UTC, bates64 approved these changes
LGTM, assigning @sderossi for second content review :shipit:

2024-05-22 15:47 UTC, merged